### ISSUE TITLE
shinyML’ is not available (for R version 3.6.0)

### ISSUE THREAD

**Issue by Eduardodudu** [JeanBertinR/dashR#1]
Trying to install the package and getting an error:

Warning in install.packages :
  package ‘shinyML’ is not available (for R version 3.6.0)

**Comment by JeanBertinR** [comment]
Sorry you're right, the package has not been published on CRAN yet. I updated Readme file in my repo.

**Comment by Eduardodudu** [comment]
Thank you!
I managed to install the package now!

Yet, I got some troubles to run the example you've given in the readme that could be updated:

```
library(shinyML)

longley2 <- longley %>%
  mutate(Year = as.Date(as.character(Year),format = "%Y"))

shiny_h2o(data =longley2,x = c("GNP_deflator","Unemployed" ,"Armed_Forces","Employed"),
          y = "GNP",date_column = "Year",share_app = TRUE,port = 3951)
```
The parameters `share_app = TRUE,port = 3951` causes this error:
```
sh: 1: ipconfig: not found
Error in system("ipconfig", intern = TRUE) : error in running command
```
When removed works fine.

Congratulations on the package! Seems promising!
